### ISSUE TITLE
Limits in List view not working

### ISSUE THREAD

**Issue by alekseikorsun** [apiology/wip-limiter#57]
Probably new shift in Asana CSS.
![image](https://github.com/apiology/wip-limiter/assets/113115075/647afd49-2951-48ee-b345-fc7f512e219b)

Saved web page: https://www.dropbox.com/scl/fi/phe98dgw444l7joe8io2x/asana.rar?rlkey=ckfnkjoo2r8tvtsk0s0n5ihxa&dl=0

**Comment by alekseikorsun** [comment]
Saved web page: https://www.dropbox.com/scl/fi/phe98dgw444l7joe8io2x/asana.rar?rlkey=ckfnkjoo2r8tvtsk0s0n5ihxa&dl=0

**Comment by apiology** [comment]
Let me know if this isn't fixed!

**Comment by alekseikorsun** [comment]
It works! Thank you
